version: '3'
services:
  app:
    image: ubank
    container_name: ubank
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/
    ports:
      - 89:80
    expose:
      - 89
